### ISSUE TITLE
Deploy AMB Live Monitoring interface 

### ISSUE THREAD

**Issue by giacomolicari** [gnosischain/issues#11]
We should deploy an instance of the AML service (https://github.com/gnosischain/tokenbridge/tree/master/alm).

It's definitely an helpful tool for everybody from the community when they need to get some deep information on the operations undertaken by Bridge validators, such as getting the status of bridge transactions.

**Comment by gMonty030** [comment]
Make the ALM bridge running, the steps are the following:
- Inside the repo's root dir exec yarn initialize and install the required dependencies if it fails. In my case was sha3, make and python3
- Afterwards, there should be the contracts built inside the dir `contracts/build/contracts/`  those are the ones failing.
- I also changed the path for the required custom modules to `const { BRIDGE_VALIDATORS_ABI, HOME_AMB_ABI } = require('../../commons')`  at the first line inside `./alm/scripts/createSnapshots.js`
- Finally, just exec npm start in the `alm dir`
Running it locally opens a tab in the browser, it doesn't work in the cluster's pod

**Comment by gMonty030** [comment]
I'm pushing the project into heroku's app `alm-tokenbridge-monitor`.
It's not getting the changes into alm folder, I guess because it's a different repo and the changes are not pushed into heroku, so I'm getting the path error from ` $ yarn build:alm && yarn build:plugin`:
` Error: Cannot find module '../contracts/build/contracts/HomeBridgeErcToNative'`

**Comment by gMonty030** [comment]
I have set this record for the ALM-monitor deployment in staging.
https://staging-alm-monitor.gnosisdev.com/

**Comment by gMonty030** [comment]
Deployed PROD environment and set CI/CD workflow for stg and prod.
https://alm-bridge-monitor.gnosischain.com/

**Comment by giacomolicari** [comment]
thank you @gMonty030 !
