### ISSUE TITLE
bug: beacon.gnosischain.com data not rendered correctly

### ISSUE THREAD

**Issue by zengzengzenghuy** [gnosischain/issues#14]
# What
1. On **Staked Ether** and **Average Balance**, showing ETH instead of GNO. 
2. Several shart plummet on the graph, even with 0 Staked ETH. 
![Screenshot from 2023-02-20 23-27-23](https://user-images.githubusercontent.com/85567868/220146684-5814dd1b-81d9-483a-8ecd-a048af11eb7d.png)

# Ref
* https://beacon.gnosischain.com/

**Comment by plato-gno** [comment]
The current beacon.gnosischain.com utilizes an outdated fork of Beaconcha.in. We have had longstanding issues making this work well, and it should be viewed as an interim stopgap. 

This will be solved longer-term thru GIP-74, where the Beaconcha.in team will support Gnosischain. This should also allow us to keep up with improvements that they are making to the product. 

https://forum.gnosis.io/t/gip-74-should-gnosisdao-support-gnosischa-in-explorer-hosted-by-beaconcha-in/6228
