### ISSUE TITLE
Dappnode: attestation rate down, no peer found

### ISSUE THREAD

**Issue by zengzengzenghuy** [gnosischain/issues#15]
# What 
Starting from Feb 17, some of the users running on Dappnode are facing several issues:

1. Attestation rate from validator went down for hours 
2. Nethermind client cannot find peers (https://github.com/gnosischain/issues/files/10815367/logs-dappnode-package-DAppNodePackage-nethermind.nethermind-xdai.dnp.dappnode.eth.2.txt)

There is no issue reported from users who run Nethermind on bare metal.

Consensus client(Teku) on Dappnode has no issue finding peers.

User who configures bootnode manually is able to find 3 peers on Nethermind.

# Potential reason:

1. New release of Nethermind v1.17 that runs on Dappnode. (as v1.16 has no related issue reported)

**Comment by zengzengzenghuy** [comment]
**Feedback from Dappnode team:**
Setting static peers and adding bootnodes for Nethermind client will solve the issue for now:
```
--Network.Bootnodes="<enode>,<enode>,..."
--Discovery.Bootnodes="<enode>,<enode>,..."
--Network.StaticPeers="<enode>,<enode>,..."
```
replace the enode with enode from [bootnodes_execution.yaml
](https://github.com/gnosischain/configs/blob/main/mainnet/bootnodes_execution.yaml)

**Comment by plato-gno** [comment]
Closing issue if there are no further complaints
