### ISSUE TITLE
bug: Checkpoint sync url error causing fail to start beacon node

### ISSUE THREAD

**Issue by zengzengzenghuy** [gnosischain/issues#16]
## What

When running beacon node, the following checkpoint sync urls return error, causing the beacon node failed to start.

Checkpoint sync url
1. "https://checkpoint.gnosischain.com/":  `CRIT Failed to start beacon node             reason: Checkpoint block at slot 8353568 is not aligned to epoch start. Please supply an aligned checkpoint with block.slot % 32 == 0`
2. "https://checkpoint.gnosis.gateway.fm/": `CRIT Failed to start beacon node             reason: Error fetching finalized block from remote: ServerMessage(ErrorMessage { code: 500, message: "not found", stacktraces: [] })`
3. "https://checkpoint-sync-gnosis.dappnode.io/": no error 

Client: 
[Lighthouse v4.0.1](https://github.com/sigp/lighthouse/releases/tag/v4.0.1)

## Refs
- [gnosischain/documentation #421 ](https://github.com/gnosischain/documentation/issues/421)

**Comment by zengzengzenghuy** [comment]
Reply from @filoozom :
The Gateway and DAppNode endpoints work for me, the Gnosis doesn't. I've reported this to DevOps, we're looking into it.

This issue might be a better fit for https://github.com/gnosischain/issues, as it's not really a documentation issue but a bug, what do you think?

**Comment by giacomolicari** [comment]
I did a test on Lighthouse v4.0.1, only checkpoint.gnosis.gateway.fm is failing, below the results.

### checkpoint.gnosischain.com ✅ 

Command:
`docker run -p 9000:9000/tcp -p 9000:9000/udp -p 127.0.0.1:5052:5052 sigp/lighthouse:v4.0.1 lighthouse beacon_node --debug-level=debug --datadir=/beacon --network gnosis --checkpoint-sync-url=https://checkpoint.gnosischain.com`

Relevant logs:
```
Apr 07 07:01:49.082 INFO Starting checkpoint sync                remote_url: https://checkpoint.gnosischain.com/, service: beacon
Apr 07 07:01:49.087 DEBG Downloading finalized block             service: beacon
Apr 07 07:01:49.287 DEBG Downloaded finalized block              service: beacon
Apr 07 07:01:49.288 DEBG Downloaded aligned finalized block      block_slot: 8371456, block_root: 0xb9cd28a03af2b97b4bd836b3e2ef2788624e2ec525fc9e99e3eedfbb59011d14, service: beacon
Apr 07 07:01:49.288 DEBG Downloading finalized state             state_root: 0xe91e7bb2ddba2a26416fb39a136d59dd00937d23efa2b213ac47ec67fbf2ec53, service: beacon
Apr 07 07:01:50.631 DEBG Downloaded finalized state              service: beacon
Apr 07 07:01:50.632 INFO Loaded checkpoint block and state       state_root: 0xe91e7bb2ddba2a26416fb39a136d59dd00937d23efa2b213ac47ec67fbf2ec53, block_root: 0xb9cd28a03af2b97b4bd836b3e2ef2788624e2ec525fc9e99e3eedfbb59011d14, slot: 8371456, service: beacon
```

### https://checkpoint.gnosis.gateway.fm 🟥 

Command:
`docker run -p 9000:9000/tcp -p 9000:9000/udp -p 127.0.0.1:5052:5052 sigp/lighthouse:v4.0.1 lighthouse beacon_node --debug-level=debug --datadir=/beacon --network gnosis --checkpoint-sync-url=https://checkpoint.gnosis.gateway.fm`

Relevant logs:
```
Apr 07 07:03:55.765 INFO Logging to file                         path: "/beacon/beacon/logs/beacon.log"
Apr 07 07:03:55.765 INFO Lighthouse started                      version: Lighthouse/v4.0.1-a53830f
Apr 07 07:03:55.765 INFO Configured for network                  name: gnosis
Apr 07 07:03:55.765 INFO Data directory initialised              datadir: /beacon
Apr 07 07:03:55.765 INFO Deposit contract                        address: 0x0b98057ea310f4d31f2a452b414647007d1645d9, deploy_block: 19469077
Apr 07 07:03:55.775 INFO Starting checkpoint sync                remote_url: https://checkpoint.gnosis.gateway.fm/, service: beacon
Apr 07 07:03:55.780 DEBG Downloading finalized block             service: beacon
Apr 07 07:03:57.042 CRIT Failed to start beacon node             reason: Error fetching finalized block from remote: ServerMessage(ErrorMessage { code: 500, message: "not found", stacktraces: [] })
Apr 07 07:03:57.048 INFO Internal shutdown received              reason: Failed to start beacon node
Apr 07 07:03:57.048 INFO Shutting down..                         reason: Failure("Failed to start beacon node")
```

### https://checkpoint-sync-gnosis.dappnode.io ✅ 

Command:
`docker run -p 9000:9000/tcp -p 9000:9000/udp -p 127.0.0.1:5052:5052 sigp/lighthouse:v4.0.1 lighthouse beacon_node --debug-level=debug --datadir=/beacon --network gnosis --checkpoint-sync-url=https://checkpoint-sync-gnosis.dappnode.io`

Relevant logs:
```
Apr 07 07:05:40.294 INFO Starting checkpoint sync                remote_url: https://checkpoint-sync-gnosis.dappnode.io/, service: beacon
Apr 07 07:05:40.298 DEBG Downloading finalized block             service: beacon
Apr 07 07:05:40.695 DEBG Downloaded finalized block              service: beacon
Apr 07 07:05:40.695 DEBG Downloaded aligned finalized block      block_slot: 8371520, block_root: 0xc34c663097cee3a490be06d50e2aa6d780f5e3905bfd35cbe711c810375c95c5, service: beacon
Apr 07 07:05:40.695 DEBG Downloading finalized state             state_root: 0x91d0436fca322812eee48b7c58a4b2371450b340251ccbecedb1de2b03ea7123, service: beacon
Apr 07 07:05:42.393 DEBG Downloaded finalized state              service: beacon
Apr 07 07:05:42.395 INFO Loaded checkpoint block and state       state_root: 0x91d0436fca322812eee48b7c58a4b2371450b340251ccbecedb1de2b03ea7123, block_root: 0xc34c663097cee3a490be06d50e2aa6d780f5e3905bfd35cbe711c810375c95c5, slot: 8371520, service: beacon
```

**Comment by giacomolicari** [comment]
@zengzengzenghuy is this issue still happening or we can close it?

**Comment by zengzengzenghuy** [comment]
Closing this issue.
