### ISSUE TITLE
beacon.gnosischain.com shows Deposit info in ETH

### ISSUE THREAD

**Issue by plato-gno** [gnosischain/issues#5]
Originally reported by @peter-gnosis

![image](https://user-images.githubusercontent.com/98335261/211497238-0b1d03de-451b-4e2e-918e-61d3ab04c370.png)

**Comment by alebanzas** [comment]
https://github.com/gnosischain/gbc-explorer/commit/53ab2578a286beb3980fd28506b03faaf1a4fd58

**Comment by alebanzas** [comment]
<img width="931" alt="Screenshot 2023-01-24 at 16 56 17" src="https://user-images.githubusercontent.com/1384638/214342729-491f9ef0-fc17-4ee1-8455-c942591b7e4d.png">
