### ISSUE TITLE
Deploy instance of Erigon<>Nimbus

### ISSUE THREAD

**Issue by giacomolicari** [gnosischain/issues#7]
As pointed out by @filoozom , soon we should run Erigon and Nimbus nodes for GnosisChain Mainnet and Chiado.
It's mostly to make sure that the software works as expected (as well as any subsequent updates).

Metrics available through Grafana dashboards will be required and those should cover both the Execution and the Consensus layer.

**Comment by gMonty030** [comment]
erigon-nimbus node deployed and syncing debugging now the stability and syncing time.

working on the monitoring endpoints.

**Comment by giacomolicari** [comment]
Enable static peers to speed-up sync process: https://github.com/ledgerwatch/erigon/pull/7052

**Comment by giacomolicari** [comment]
I'm closing this issue for the moment, feel free to re-open it in case more work/assistance is needed on this specific topic.
